<?php

/**
 * @author Florian Rowehy
 * @link https://github.com/Florian-Rowehy
 */

return [
    'école',
    'faute',
    'grammaire',
    'éducation',
    'punition',
    'bulletin',
    'institutrice',
    'étude',
    'problème',
    'cours',
    'classe',
    'devoir',
    'élève',
    'instituteur',
    'leçon',
    'savoir',
    'science',
    'apprentissage',
    'cahier',
    'mot',
    'écolier',
    'parole',
    'récréation',
    'rentrée',
    'vacance',
    'exemple',
    'instruction',
    'livre',
    'page',
    'stylo',
    'math',
    'physique',
    'chimie',
    'collège',
    'lycée',
    'formation',
    'scolaire',
    'enseignement',
    'correction',
    'poésie',
    'poème',
    'dictionnaire',
    'rédaction',
    'note',
    'question',
    'examen',
    'oral',
    'travail',
];
